import { Typography } from '@material-ui/core';
import type { NextPage } from 'next';
import Head from 'next/head';

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Typography variant="h6">Home</Typography>
      </main>
      <footer>Footer</footer>
    </div>
  );
};

export default Home;
