import { getIsValidEmail, getOnlyNumber } from '@justinaus/shared';
import { Typography } from '@material-ui/core';
import type { NextPage } from 'next';
import Head from 'next/head';

const Home: NextPage = () => {
  console.log(
    'test',
    getOnlyNumber(`123jjj123`),
    getIsValidEmail('123@naver.com'),
  );

  return (
    <div>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Typography variant="h6" className="mb-4">
          Home
        </Typography>
        <div>111</div>
      </main>
      <footer>Footer</footer>
    </div>
  );
};

export default Home;
